name: Build backend
on: [push]
jobs:
  back-end:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'
          cache: maven

      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE recepti_db;' -uroot -proot

      - name: Build and test with Maven
        run: mvn -B package --file pom.xml
        working-directory: app
